### ISSUE TITLE
Label for edges rendering out of bounds for Postion.Left & Position.Right

### ISSUE THREAD

**Issue by cliffordfajardo** [wbkd/react-flow#1796]
### Describe the Bug

When using the `targetPosition` option for a node with either `Position.Left` or `Position.Right` value,  the label text gets rendered completely off of the edge pathway.

When using  `Position.Top` or `Position.Bottom` for the `targetPosition` value, the label is rendered on the edge pathway and things look as expected

### Steps to Reproduce the Bug or Issue

1. Visit either of the following codesanbox's
- `react-flow-renderer` V10: https://codesandbox.io/s/stoic-moore-432gq?file=/src/examples/Example2/index.tsx
- `react-flow-renderer` V9:  https://codesandbox.io/s/mystifying-elion-p62yi?file=/src/examples/Example2/index.tsx

2. Swap the `targetPosition` value to either `Position.Left` or `Position.Right` & observer that the label will render outside of the edge path.

NOTE: I have 2 example components in each codesanbox
  -  `<Example1 />`: renders a regular ReactFlow visualization without custom nodes or edges
  -  `<Example2 />`: renders a 1 custom component that is using `<Handle>`'s
  - This is to illustrate that it is effects node that using different rendering strategies (default rendering vs custom node + handle)

### Expected behavior

As a user using this feature, I expected:

1. To see the label text rendered on the edge patway, but not outside of it
   ![CleanShot 2021-12-27 at 15 52 56@2x](https://user-images.githubusercontent.com/6743796/147514333-f1f7d4b5-ea7d-4a73-918d-29b53eca429f.png)

2. To see the label  text rendered on the edge pathway if there is sufficient space available to render the text
   - if you see the video below, this may add more context on this point ^

### Screenshots or Videos

https://user-images.githubusercontent.com/6743796/147514502-960b4656-a891-413c-8ea7-5ddef2e6b512.mp4

### Platform

- OS: MacOS
- Browser: Google Chrome 
- Version: latest (Version 96.0.4664.110)

**Comment by Ipicky22** [comment]
Hi @cliffordfajardo !

I created a graph with an element which is always centered in the middle of the edges. I did it under V9.
I think I found several errors in your code.

At first I think it's better to create a customEdge, which I didn't see in your code.
If we take the React Flow documentation : https://reactflow.dev/examples/edges/ , we can see that all the edges are custom made.

When you have created your custom edge, you can find the center of the edge using the getEdgeCenter function, provided by react-flow-renderer. You can then assign the positions to your object which will always be centered.

Here is an example of a custom edge that continually centers "Hello" :

```typescript
import { getBezierPath, getMarkerEnd, getEdgeCenter } from 'react-flow-renderer';

const foreignObjectSize = 40;

interface CustomEdgeProps {
    id: string;
    sourceX: number,
    sourceY: number,
    targetX: number,
    targetY: number,
    sourcePosition: any,
    targetPosition: any,
    style: any,
    data: any,
    arrowHeadType: any,
    markerEndId: any,
}

function CustomEdge({
    id,
    sourceX,
    sourceY,
    targetX,
    targetY,
    sourcePosition,
    targetPosition,
    style,
    data,
    arrowHeadType = "arrowclosed",
    markerEndId,
}: CustomEdgeProps) {

    const edgePath = getBezierPath({ sourceX, sourceY, sourcePosition, targetX, targetY, targetPosition });
    const markerEnd = getMarkerEnd(arrowHeadType, markerEndId);
    const [edgeCenterX, edgeCenterY] = getEdgeCenter({
        sourceX,
        sourceY,
        targetX,
        targetY,
    });

    return (
        <>
            <path
                id={id}
                style={style}
                className="react-flow__edge-path"
                d={edgePath}
                markerEnd={markerEnd}
            />
            <foreignObject
                width={foreignObjectSize}
                height={foreignObjectSize}
                x={edgeCenterX - foreignObjectSize / 2}
                y={edgeCenterY - foreignObjectSize / 2}
                className="edgebutton-foreignobject"
                requiredExtensions="http://www.w3.org/1999/xhtml"
            >

                <div>Hello</div>
            </foreignObject>
        </>
    );
}

export default CustomEdge;
```

I also refer you to the custom edge documentation : https://reactflow.dev/docs/api/edge-types/
Don't forget to add the edgeTypes parameter in the ReactFlow components.

I don't know if my solution is the best way to do it, but it works.

Hope this helps you solve your problem.

**Comment by kuldeepkeshwar** [comment]
@cliffordfajardo @Ipicky22 
i had similar problem, I found `getEdgeCenter` doesn't work always(varies with sharpe of edge) and doing all geometry calculation and finding point on curve is hard. 

easy way for it is using methods of `SVGGeometryElement`
so I built a hook :-) 

```js
function usePointsOnPath(edgePath: string, lengths: number[]) {
// edgePath is curve path & lengths is array points (0<t<1) on curve. 

  const [points, setPoints] = useState<(Point | undefined)[]>([]);
  const pathRef = useRef<SVGPathElement>(null);
  useDeepCompareEffect(() => {
    const pathEl = pathRef.current;
    if (pathEl) {
      const totalLength = pathEl.getTotalLength();
      setPoints(lengths.map((length) => pathEl.getPointAtLength(totalLength * length)));
    }
  }, [edgePath, lengths]);
  return { points, pathRef };
 }
```
```js
function CustomEdge(){
const edgePath = getCurve({
    sourceX,
    sourceY,
    sourcePosition,
    targetX,
    targetY,
    targetPosition
  });
  const markerEnd = getMarkerEnd(arrowHeadType, markerEndId);

  const center = 0.5;
  const {
    points: [centerPoint],
    pathRef
  } = usePointsOnPath(edgePath, [center]);
  ....
  return <><path
          ref={pathRef}
          d={edgePath}
          ...
        />
        <foreignObject
                width={foreignObjectSize}
                height={foreignObjectSize}
                x={centerPoint.x - foreignObjectSize / 2}
                y={centerPoint.Y - foreignObjectSize / 2}
                className="edgebutton-foreignobject"
                requiredExtensions="http://www.w3.org/1999/xhtml"
            >

                <div>Hello</div>
            </foreignObject>
            </>
}
```
Hope this helps 

> Note: this is a pseudo code

**Comment by moklick** [comment]
Hey. This got fixed in v10.0.5.  We now have `getBezierEdgeCenter` and `getSimpleBezierEdgeCenter` util functions to receive the correct center. https://reactflow.dev/docs/api/edges/edge-utils/#getbezieredgecenter

**Comment by micleners** [comment]
@moklick I was still getting the "center" at the wrong position when I used either `getBezierEdgeCenter` or `getSimpleBezierEdgeCenter`.

It appears that the issue is when the source and target are not "opposite" (e.g. top/bottom, left/right are ok, whereas top/right or bottom/left are off-center).

Using @kuldeepkeshwar's solution works in our case 🙏
