### ISSUE TITLE
Reactflow bundling error in storybook

### ISSUE THREAD

**Issue by ashwanth1109** [wbkd/react-flow#2652]
### Describe the Bug

When I install reactflow (v11.3.2) and use it in a story, the storybook server fails to start with the following errors:

```
ERROR in ./node_modules/.pnpm/registry.npmjs.org+@reactflow+minimap@11.2.2_sfoxds7t5ydpegc3knd667wn6m/node_modules/@reactflow/minimap/dist/esm/index.js 41:31
Module parse failed: Unexpected token (41:31)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|     const svg = useRef(null);
|     const { boundingRect, viewBB, nodes, rfId, nodeOrigin } = useStore(selector, shallow);
>     const elementWidth = style?.width ?? defaultWidth;
|     const elementHeight = style?.height ?? defaultHeight;
|     const nodeColorFunc = getAttrFunction(nodeColor);
...
```

```
ERROR in ./node_modules/.pnpm/registry.npmjs.org+@reactflow+controls@11.0.6_sfoxds7t5ydpegc3knd667wn6m/node_modules/@reactflow/controls/dist/esm/index.js 43:17
Module parse failed: Unexpected token (43:17)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|     const onZoomInHandler = () => {
|         zoomIn();
>         onZoomIn?.();
|     };
|     const onZoomOutHandler = () => {
...
```

```
ERROR in ./node_modules/.pnpm/registry.npmjs.org+@reactflow+core@11.3.1_sfoxds7t5ydpegc3knd667wn6m/node_modules/@reactflow/core/dist/esm/index.js 43:19
Module parse failed: Unexpected token (43:19)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
| function Attribution({ proOptions, position = 'bottom-right' }) {
>     if (proOptions?.hideAttribution) {
|         return null;
|     }
...
```

```
ERROR in ./node_modules/.pnpm/registry.npmjs.org+@reactflow+node-toolbar@1.0.1_sfoxds7t5ydpegc3knd667wn6m/node_modules/@reactflow/node-toolbar/dist/esm/index.js 8:42
Module parse failed: Unexpected token (8:42)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| import { createPortal } from 'react-dom';
|
> const selector = (state) => state.domNode?.querySelector('.react-flow__renderer');
| function NodeToolbarPortal({ children }) {
|     const wrapperRef = useStore(selector);
...
```

### Steps to Reproduce the Bug or Issue

1. Install React Flow
2. Create a simple flow
3. Install storybook
4. Create a story that renders the react component with the simple flow
5. Run the storybook server

### Expected behavior

I expected storybook to be able to bundle reactflow dependencies in my story

### Screenshots or Videos

![2022-12-07 13_04_32-Git Bash](https://user-images.githubusercontent.com/32328857/206116701-1336f94d-fcff-4737-96cd-4f823d0a94ae.png)

### Platform

- OS: Windows
- Browser: Not Relevant
- Version: 11.3.2

### Additional context

Note that a similar issue has also been reported by others on stackoverflow here:
https://stackoverflow.com/questions/74423572/importing-reactflow-v11-causes-error-module-parse-failed-unexpected-token

Also note that we've had our storybook server running for almost a year now (meaning various other libraries and stories have been created so far). This error occurred after we started using reactflow, and if we comment out the `<ReactFlow>` component, the storybook server compiles successfully.

**Comment by erikbernard** [comment]
I had a similar problem.

I solved it this way
`install npm install --save --save-exact react-scripts@5.0.0`

Then I deleted the nodeModule folders, and did the installation again.
`npm install`

**Comment by moklick** [comment]
yep, with react-scripts@5 it should work.

**Comment by yakirp** [comment]
It's also happened to me; Installing react-script didn't help.

**Comment by avishwakarmaplex** [comment]
@moklick why does reactflow requires react-script, after adding react-script to my library project its throwing bunch of errors at the time of its build like the following: 

[webpack-cli] TypeError: The 'compilation' argument must be an instance of Compilation
    at Function.getCompilationHooks (C:\Dev\Git\spa\thumb-components\node_modules\webpack\lib\NormalModule.js:227:10)
    at getCompilationHooks (C:\Dev\Git\spa\thumb-components\node_modules\@ckeditor\ckeditor5-dev-webpack-plugin\lib\servetranslations.js:207:22)
    at C:\Dev\Git\spa\thumb-components\node_modules\@ckeditor\ckeditor5-dev-webpack-plugin\lib\servetranslations.js:97:3
    at Hook.eval [as call] (eval at create (C:\Dev\Git\spa\thumb-components\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:100:1)
    at Hook.CALL_DELEGATE [as _call] (C:\Dev\Git\spa\thumb-components\node_modules\tapable\lib\Hook.js:14:14)
    at Compiler.newCompilation (C:\Dev\Git\spa\thumb-components\packages\thumb-richtexteditor\node_modules\webpack\lib\Compiler.js:1031:26)
    at C:\Dev\Git\spa\thumb-components\packages\thumb-richtexteditor\node_modules\webpack\lib\Compiler.js:1073:29
    at Hook.eval [as callAsync] (eval at create (C:\Dev\Git\spa\thumb-components\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\Dev\Git\spa\thumb-components\node_modules\tapable\lib\Hook.js:18:14)
    at Compiler.compile (C:\Dev\Git\spa\thumb-components\packages\thumb-richtexteditor\node_modules\webpack\lib\Compiler.js:1068:28)

**Comment by avishwakarmaplex** [comment]
I think i have fixed that, ckeditor/ckeditor5-dev-webpack-plugin is deprecated


But i'm getting new error, it seems webpack5 have removed this module 'webpack/lib/MultiEntryPlugin', does anyone know how to fix this ? 

info @storybook/react v6.5.13
info
ERR! Error: Cannot find module 'webpack/lib/MultiEntryPlugin'
ERR! Require stack:
ERR! - C:\Dev\Git\spa\plex-react-components\node_modules\globalize-webpack-plugin\ProductionModePlugin.js
ERR! - C:\Dev\Git\spa\plex-react-components\node_modules\globalize-webpack-plugin\index.js
ERR! - C:\Dev\Git\spa\plex-react-components\.storybook\webpack-extend.js
ERR! - C:\Dev\Git\spa\plex-react-components\.storybook\main.js
ERR! - C:\Dev\Git\spa\plex-react-components\node_modules\@storybook\core-common\dist\cjs\utils\interpret-require.js
ERR! - C:\Dev\Git\spa\plex-react-components\node_modules\@storybook\core-common\dist\cjs\utils\load-custom-presets.js
ERR! - C:\Dev\Git\spa\plex-react-components\node_modules\@storybook\core-common\dist\cjs\presets.js
ERR! - C:\Dev\Git\spa\plex-react-components\node_modules\@storybook\core-common\dist\cjs\index.js
ERR! - C:\Dev\Git\spa\plex-react-components\node_modules\@storybook\core-server\dist\cjs\index.js
ERR! - C:\Dev\Git\spa\plex-react-components\node_modules\@storybook\core\dist\cjs\server.js
ERR! - C:\Dev\Git\spa\plex-react-components\node_modules\@storybook\core\server.js
ERR! - C:\Dev\Git\spa\plex-react-components\node_modules\@storybook\react\dist\cjs\server\index.js
ERR! - C:\Dev\Git\spa\plex-react-components\node_modules\@storybook\react\bin\index.js
ERR!     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
ERR!     at Function.Module._load (node:internal/modules/cjs/loader:841:27)
ERR!     at Module.require (node:internal/modules/cjs/loader:1067:19)
ERR!     at require (node:internal/modules/cjs/helpers:103:18)
ERR!     at Object.<anonymous> (C:\Dev\Git\spa\plex-react-components\node_modules\globalize-webpack-plugin\ProductionModePlugin.js:5:26)
ERR!     at Module._compile (node:internal/modules/cjs/loader:1165:14)
ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
ERR!     at Module.load (node:internal/modules/cjs/loader:1043:32)
ERR!     at Function.Module._load (node:internal/modules/cjs/loader:878:12)
ERR!     at Module.require (node:internal/modules/cjs/loader:1067:19)
ERR!     at require (node:internal/modules/cjs/helpers:103:18)
ERR!     at Object.<anonymous> (C:\Dev\Git\spa\plex-react-components\node_modules\globalize-webpack-plugin\index.js:4:30)
ERR!     at Module._compile (node:internal/modules/cjs/loader:1165:14)
ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
ERR!     at Module.load (node:internal/modules/cjs/loader:1043:32)
ERR!     at Function.Module._load (node:internal/modules/cjs/loader:878:12)
ERR!  Error: Cannot find module 'webpack/lib/MultiEntryPlugin'
ERR! Require stack:
ERR! - C:\Dev\Git\spa\plex-react-components\node_modules\globalize-webpack-plugin\ProductionModePlugin.js
ERR! - C:\Dev\Git\spa\plex-react-components\node_modules\globalize-webpack-plugin\index.js
ERR! - C:\Dev\Git\spa\plex-react-components\.storybook\webpack-extend.js
ERR! - C:\Dev\Git\spa\plex-react-components\.storybook\main.js
ERR! - C:\Dev\Git\spa\plex-react-components\node_modules\@storybook\core-common\dist\cjs\utils\interpret-require.js
ERR! - C:\Dev\Git\spa\plex-react-components\node_modules\@storybook\core-common\dist\cjs\utils\load-custom-presets.js
ERR! - C:\Dev\Git\spa\plex-react-components\node_modules\@storybook\core-common\dist\cjs\presets.js
ERR! - C:\Dev\Git\spa\plex-react-components\node_modules\@storybook\core-common\dist\cjs\index.js
ERR! - C:\Dev\Git\spa\plex-react-components\node_modules\@storybook\core-server\dist\cjs\index.js
ERR! - C:\Dev\Git\spa\plex-react-components\node_modules\@storybook\core\dist\cjs\server.js
ERR! - C:\Dev\Git\spa\plex-react-components\node_modules\@storybook\core\server.js
ERR! - C:\Dev\Git\spa\plex-react-components\node_modules\@storybook\react\dist\cjs\server\index.js
ERR! - C:\Dev\Git\spa\plex-react-components\node_modules\@storybook\react\bin\index.js
ERR!     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
ERR!     at Function.Module._load (node:internal/modules/cjs/loader:841:27)
ERR!     at Module.require (node:internal/modules/cjs/loader:1067:19)
ERR!     at require (node:internal/modules/cjs/helpers:103:18)
ERR!     at Object.<anonymous> (C:\Dev\Git\spa\plex-react-components\node_modules\globalize-webpack-plugin\ProductionModePlugin.js:5:26)
ERR!     at Module._compile (node:internal/modules/cjs/loader:1165:14)
ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
ERR!     at Module.load (node:internal/modules/cjs/loader:1043:32)
ERR!     at Function.Module._load (node:internal/modules/cjs/loader:878:12)
ERR!     at Module.require (node:internal/modules/cjs/loader:1067:19)
ERR!     at require (node:internal/modules/cjs/helpers:103:18)
ERR!     at Object.<anonymous> (C:\Dev\Git\spa\plex-react-components\node_modules\globalize-webpack-plugin\index.js:4:30)
ERR!     at Module._compile (node:internal/modules/cjs/loader:1165:14)
ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
ERR!     at Module.load (node:internal/modules/cjs/loader:1043:32)
ERR!     at Function.Module._load (node:internal/modules/cjs/loader:878:12) {
ERR!   code: 'MODULE_NOT_FOUND',
ERR!   requireStack: [
ERR!     'C:\\Dev\\Git\\spa\\plex-react-components\\node_modules\\globalize-webpack-plugin\\ProductionModePlugin.js',
ERR!     'C:\\Dev\\Git\\spa\\plex-react-components\\node_modules\\globalize-webpack-plugin\\index.js',
ERR!     'C:\\Dev\\Git\\spa\\plex-react-components\\.storybook\\webpack-extend.js',
ERR!     'C:\\Dev\\Git\\spa\\plex-react-components\\.storybook\\main.js',
ERR!     'C:\\Dev\\Git\\spa\\plex-react-components\\node_modules\\@storybook\\core-common\\dist\\cjs\\utils\\interpret-require.js',
ERR!     'C:\\Dev\\Git\\spa\\plex-react-components\\node_modules\\@storybook\\core-common\\dist\\cjs\\utils\\load-custom-presets.js',
ERR!     'C:\\Dev\\Git\\spa\\plex-react-components\\node_modules\\@storybook\\core-common\\dist\\cjs\\presets.js',
ERR!     'C:\\Dev\\Git\\spa\\plex-react-components\\node_modules\\@storybook\\core-common\\dist\\cjs\\index.js',
ERR!     'C:\\Dev\\Git\\spa\\plex-react-components\\node_modules\\@storybook\\core-server\\dist\\cjs\\index.js',
ERR!     'C:\\Dev\\Git\\spa\\plex-react-components\\node_modules\\@storybook\\core\\dist\\cjs\\server.js',
ERR!     'C:\\Dev\\Git\\spa\\plex-react-components\\node_modules\\@storybook\\core\\server.js',
ERR!     'C:\\Dev\\Git\\spa\\plex-react-components\\node_modules\\@storybook\\react\\dist\\cjs\\server\\index.js',
ERR!     'C:\\Dev\\Git\\spa\\plex-react-components\\node_modules\\@storybook\\react\\bin\\index.js'
ERR!   ]
ERR! }

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.

node:internal/modules/cjs/loader:995
  const err = new Error(message);
              ^

Error: Cannot find module 'webpack/lib/MultiEntryPlugin'
Require stack:
- C:\Dev\Git\spa\plex-react-components\node_modules\globalize-webpack-plugin\ProductionModePlugin.js
- C:\Dev\Git\spa\plex-react-components\node_modules\globalize-webpack-plugin\index.js
- C:\Dev\Git\spa\plex-react-components\.storybook\webpack-extend.js
- C:\Dev\Git\spa\plex-react-components\.storybook\main.js
- C:\Dev\Git\spa\plex-react-components\node_modules\@storybook\core-common\dist\cjs\utils\interpret-require.js
- C:\Dev\Git\spa\plex-react-components\node_modules\@storybook\core-common\dist\cjs\utils\load-custom-presets.js
- C:\Dev\Git\spa\plex-react-components\node_modules\@storybook\core-common\dist\cjs\presets.js
- C:\Dev\Git\spa\plex-react-components\node_modules\@storybook\core-common\dist\cjs\index.js
- C:\Dev\Git\spa\plex-react-components\node_modules\@storybook\core-server\dist\cjs\index.js
- C:\Dev\Git\spa\plex-react-components\node_modules\@storybook\core\dist\cjs\server.js
- C:\Dev\Git\spa\plex-react-components\node_modules\@storybook\core\server.js
- C:\Dev\Git\spa\plex-react-components\node_modules\@storybook\react\dist\cjs\server\index.js
- C:\Dev\Git\spa\plex-react-components\node_modules\@storybook\react\bin\index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Function.Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1067:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (C:\Dev\Git\spa\plex-react-components\node_modules\globalize-webpack-plugin\ProductionModePlugin.js:5:26)
    at Module._compile (node:internal/modules/cjs/loader:1165:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
    at Module.load (node:internal/modules/cjs/loader:1043:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1067:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (C:\Dev\Git\spa\plex-react-components\node_modules\globalize-webpack-plugin\index.js:4:30)
    at Module._compile (node:internal/modules/cjs/loader:1165:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
    at Module.load (node:internal/modules/cjs/loader:1043:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Dev\\Git\\spa\\plex-react-components\\node_modules\\globalize-webpack-plugin\\ProductionModePlugin.js',
    'C:\\Dev\\Git\\spa\\plex-react-components\\node_modules\\globalize-webpack-plugin\\index.js',
    'C:\\Dev\\Git\\spa\\plex-react-components\\.storybook\\webpack-extend.js',
    'C:\\Dev\\Git\\spa\\plex-react-components\\.storybook\\main.js',
    'C:\\Dev\\Git\\spa\\plex-react-components\\node_modules\\@storybook\\core-common\\dist\\cjs\\utils\\interpret-require.js',
    'C:\\Dev\\Git\\spa\\plex-react-components\\node_modules\\@storybook\\core-common\\dist\\cjs\\utils\\load-custom-presets.js',
    'C:\\Dev\\Git\\spa\\plex-react-components\\node_modules\\@storybook\\core-common\\dist\\cjs\\presets.js',
    'C:\\Dev\\Git\\spa\\plex-react-components\\node_modules\\@storybook\\core-common\\dist\\cjs\\index.js',
    'C:\\Dev\\Git\\spa\\plex-react-components\\node_modules\\@storybook\\core-server\\dist\\cjs\\index.js',
    'C:\\Dev\\Git\\spa\\plex-react-components\\node_modules\\@storybook\\core\\dist\\cjs\\server.js',
    'C:\\Dev\\Git\\spa\\plex-react-components\\node_modules\\@storybook\\core\\server.js',
    'C:\\Dev\\Git\\spa\\plex-react-components\\node_modules\\@storybook\\react\\dist\\cjs\\server\\index.js',
    'C:\\Dev\\Git\\spa\\plex-react-components\\node_modules\\@storybook\\react\\bin\\index.js'

**Comment by moklick** [comment]
It doesn't require react-scripts but you need to transpile it. That depends on your setup.

**Comment by avishwakarmaplex** [comment]
@moklick I would like to know that
since i'm using storybook 6.3.3 which requires webpack 4, does react-flow requires webpack, if yes what would be the compatible version w.r.t webpack 4, since i'm also using ckeditor with webpack 4

**Comment by avishwakarmaplex** [comment]
@moklick did you got a chance to look over the error on my earlier comment ?

**Comment by JanuZz** [comment]
Hey there 👋 i had the same exact issue earlier. What does your `./storybook/main.js` look like?

**Comment by avishwakarmaplex** [comment]
@JanuZz 
Matter of fact i did i added @storybook/preset-create-react-app dependency, and it's throwing the same error 


ERROR in ./node_modules/@reactflow/minimap/dist/esm/index.js 41:31
Module parse failed: Unexpected token (41:31)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|     const svg = useRef(null);
|     const { boundingRect, viewBB, nodes, rfId, nodeOrigin } = useStore(selector, shallow);
>     const elementWidth = style?.width ?? defaultWidth;
|     const elementHeight = style?.height ?? defaultHeight;
|     const nodeColorFunc = getAttrFunction(nodeColor);
 @ ./node_modules/reactflow/dist/esm/index.js 3:0-35 3:0-35
 @ ./packages/thumb-react-flows/src/FlowCanvas.tsx
 @ ./packages/thumb-react-flows/src/FlowCanvas.stories.tsx
 @ ./packages sync ^\.(?:(?:^|[\\/]|(?:(?:(?!(?:^|[\\/])\.).)*?)[\\/])(?!\.)(?=.)[^\\/]*?\.stories\.(tsx|js|mdx))$
 @ ./generated-stories-entry.js
 @ multi ./node_modules/@storybook/core-client/dist/esm/globals/polyfills.js ./node_modules/@storybook/core-client/dist/esm/globals/globals.js (webpack)-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined ./storybook-init-framework-entry.js ./node_modules/@storybook/react/dist/esm/client/docs/config-generated-config-entry.js ./node_modules/@storybook/react/dist/esm/client/preview/config-generated-config-entry.js ./node_modules/@storybook/addon-docs/preview.js-generated-config-entry.js ./node_modules/@storybook/addon-actions/preview.js-generated-config-entry.js ./.storybook/preview.js-generated-config-entry.js ./generated-stories-entry.js


However when i hit yarn start, i saw one of the error saying failed to resolve react-script, but i did an clean install(rimraf node_module followed by install)

info @storybook/react v6.5.13
info
info => Loading presets
info => Loading custom manager config

attention => Storybook now collects completely anonymous telemetry regarding usage.
This information is used to shape Storybook's roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://storybook.js.org/telemetry

info Addon-docs: using MDX1
info => Using PostCSS preset with postcss@7.0.36
**ERR! Failed to resolve a `react-scripts` package.**
info => Loading custom manager config
info => Using default Webpack4 setup
10% building 3/9 modules 6 active C:\Dev\Git\spa\thumb-react-components\node_modules\@storybook\addon-actions\preview.jsBrowserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db



This is how my ./storybook/.main.js looks alike

```
const prettierConfig = require("../.prettierrc");
const extendWebpack = require("./webpack-extend");

module.exports = {
  stories: ["../packages/**/*.stories.@(tsx|js|mdx)"],
  addons: [
    // toolbar
    { name: "@storybook/addon-docs", sourceLoaderOptions: { prettierConfig } },
    "@storybook/addon-viewport",
    "@storybook/addon-controls",

    // panels
    "../packages/storybook-state/src/preset.js",
    "@storybook/addon-actions",
    "@storybook/addon-toolbars",

    // presets
    "@storybook/addon-postcss",
    "@storybook/preset-create-react-app"
  ],
  framework: "@storybook/react",
  webpackFinal: extendWebpack
};


```

**Comment by JanuZz** [comment]
@avishwakarmaplex that's odd, I can run it fine with the same `./storybook/main.js` as you. My best guess would be to find some way to upgrade to the latest version of storybook. As I understand it, they changed quite a bit about how they transpile stuff

**Comment by avishwakarmaplex** [comment]
@JanuZz so problem is i'm using storybook v6.3.3 and using webpack 4,  and since i'm also using ckeditor, it seems like webpack 4 doesn't works well with react-script latest version, it complains a lot and even storybook version also requires webpack4 for the version currently i'm using.

I had heard that storybook is gonna release a new version which won't require webpack, but i don't know when !!!!!!

**Comment by JanuZz** [comment]
@avishwakarmaplex and there's no way to get ckeditor to work with storybook v6.5.15? Or are there other things limiting your storybook version?

The only real suggestion I have to solve your problem is to update storybook

**Comment by avishwakarmaplex** [comment]
@JanuZz There is one thing that is kind of blocking me to upgrade to latest storybook is globalize-webpack-plugin it only works with webpack 4 and below and doesn't work with webpack 5, since i have to remove all my localization code it would be cumbersome which is right now functional 


// webpack-extend.js
```
const { resolve } = require("path");
**const GlobalizePlugin = require("globalize-webpack-plugin");**
const { locales } = require("@locales/culture-locales");
const merge = require("webpack-merge");
const { styles } = require("@ckeditor/ckeditor5-dev-utils");
const CKEditorWebpackPlugin = require("@ckeditor/ckeditor5-dev-webpack-plugin");

const sassModuleRegex = /\.module\.s[ac]ss$/;

module.exports = async (config, { configType }) => {
  // alter storybook config to support CKEditor
  config.module.rules = config.module.rules.map(rule => {
    if (rule.test && rule.test.test("/ckeditor5-/theme/anything.css")) {
      rule.exclude = [...(rule.exclude || []), /ckeditor5-[^/\\]+[/\\]theme[/\\].+\.css$/];
    } else if (rule.test && rule.test.test("/ckeditor5-/theme/anything.svg")) {
      rule.exclude = [
        ...(rule.exclude || []),
        /ckeditor5-[^/\\]+[/\\]theme[/\\]icons[/\\][^/\\]+\.svg$/,
        /ckeditor5-[^/\\]+[/\\]theme[/\\].+\.css$/
      ];
    }
    return rule;
  });

  return merge(config, {
    module: {
      rules: [
        {
          test: /\.s[ac]ss$/,
          exclude: sassModuleRegex,
          loaders: ["style-loader", "css-loader", "postcss-loader", "sass-loader"],
          include: resolve(__dirname, "../packages")
        },
        {
          test: sassModuleRegex,
          include: resolve(__dirname, "../packages"),
          loaders: [
            "style-loader",
            {
              loader: "css-loader",
              options: {
                importLoaders: 1,
                modules: true,
                camelCase: true,
                localIdentName: "[name]__[local]___[hash:base64:5]"
              }
            },
            "postcss-loader",
            "sass-loader"
          ]
        },
        {
          test: /ckeditor5-[^/\\]+[/\\]theme[/\\]icons[/\\][^/\\]+\.svg$/,
          use: ["raw-loader"]
        },
        {
          test: /ckeditor5-[^/\\]+[/\\]theme[/\\].+\.css/,
          use: [
            {
              loader: "style-loader",
              options: {
                injectType: "singletonStyleTag"
              }
            },
            {
              loader: "postcss-loader",
              options: styles.getPostCssConfig({
                themeImporter: {
                  themePath: require.resolve("@ckeditor/ckeditor5-theme-lark")
                },
                minify: true,
                sourceMap: true
              })
            }
          ]
        }
      ]
    },
    plugins: [
      new GlobalizePlugin({
        production: false,
        developmentLocale: "en-US",
        supportedLocales: Object.keys(locales),
        output: "i18n/[locale].[chunkhash].js",
        cldr: locale => locales[locale]
      }),
      new CKEditorWebpackPlugin({ language: "en", buildAllTranslationsToSeparateFiles: true })
    ],
    resolve: {
      alias: {
        "@thumb/culture-timezone": resolve(
          __dirname,
          "../node_modules/@thumb/culture-timezone/dist/thumb-culture-timezone.js"
        ),
        "@utils": resolve(__dirname, "../packages/thumb-components/src/utils"),
        "@hooks": resolve(__dirname, "../packages/thumb-components/src/hooks"),
        "@arrays-immutable": resolve(__dirname, "../packages/thumb-components/src/arrays-immutable"),
        "@components": resolve(__dirname, "../packages/thumb-components/src/components")
      },
      modules: [
        resolve(__dirname, "../packages/thumb-charts/src"),
        resolve(__dirname, "../packages/thumb-components/src"),
        resolve(__dirname, "../packages/thumb-richtexteditor/src")
      ]
    }
  });
};
```

any tips ?

**Comment by JanuZz** [comment]
@avishwakarmaplex Not really, it's not anything I've delt with before, but my best guess is look for a way to get the plug-ins to work with storybook 6.5.15 or at least above 6.5

**Comment by moklick** [comment]
I tried to add storybook to our next-js example app and it works fine: https://github.com/wbkd/react-flow-example-apps/blob/storybook/reactflow-nextjs/src/stories/Flow.stories.tsx 

Please update to the latest storybook version and feel free to re-open if the issue still occurs.

**Comment by avishwakarmaplex** [comment]
@moklick / @JanuZz 
I was able to build reactflow with my library project

but i ended up with this error

![image](https://user-images.githubusercontent.com/72560398/214005759-ff696580-0628-40de-84ac-800aaaa4f937.png)

Do you know what could have gone wrong?

**Comment by JanuZz** [comment]
My best bet is that it might be related to https://github.com/d3/d3-zoom/issues/167, but its not something I've seen before

TLDR; You might have multiple versions of d3-selection installed, check your `package-lock.json`

**Comment by avishwakarmaplex** [comment]
@JanuZz 
Yeah i kind of do
so in my package.json it has

//package.json 
"devDependencies":  { 
   "c3": "^0.7.13",
    "d3": "^5.8.0"
  // More packages
  }
  
  I don't know what version of d3 does reactflow requires 
  
  So i'm using yarn, so when i installed reactflow it did updated yarn.lock file 
  
`	"@reactflow/background@11.1.2":
	  version "11.1.2"
	  resolved "https://registry.npmjs.org/@reactflow/background/-/background-11.1.2.tgz#6f4e5d8ae6bc0b5d76f4394ab7a2ae59b568aa02"
	  integrity sha512-A/Hfah+l9C7mzZ4IG2Kw9phOTLUPIie2zRFE59EXEwHUmSS91SPaFE464ydclj1Y4+OEYZb7cTiaHiKEzp3OkA==
	  dependencies:
		"@reactflow/core" "11.4.2"
		classcat "^5.0.3"
		zustand "^4.3.1"

	"@reactflow/controls@11.1.2":
	  version "11.1.2"
	  resolved "https://registry.npmjs.org/@reactflow/controls/-/controls-11.1.2.tgz#2701c32c7ae718bb7c59fb99e64e33a37799f386"
	  integrity sha512-XyZuMOxSmqYnH+MpRxMiZS8uCdPqaWg4Ju4Sv4B1WW6ae5YsgqG9MGgHF1mOc63BhK6gchRtxV9mW+EJoB+6Pg==
	  dependencies:
		"@reactflow/core" "11.4.2"
		classcat "^5.0.3"

	"@reactflow/core@11.4.2":
	  version "11.4.2"
	  resolved "https://registry.npmjs.org/@reactflow/core/-/core-11.4.2.tgz#70d6e7f1d33b93cc8a75a72192a06397bc05c9cf"
	  integrity sha512-JVKFNJ3LTVyQXkZCnk5X5bGo01k4uCyYLlenkCEHL7HZ65v9k6WjD+tY4mdO/t1LIZ18t3j7wlhEhvTrjupN9Q==
	  dependencies:
		"@types/d3" "^7.4.0"
		"@types/d3-drag" "^3.0.1"
		"@types/d3-selection" "^3.0.3"
		"@types/d3-zoom" "^3.0.1"
		classcat "^5.0.3"
		d3-drag "^3.0.0"
		d3-selection "^3.0.0"
		d3-zoom "^3.0.0"
		zustand "^4.3.1"

	"@reactflow/minimap@11.3.2":
	  version "11.3.2"
	  resolved "https://registry.npmjs.org/@reactflow/minimap/-/minimap-11.3.2.tgz#5d00a2f6d74c4da4c5740985126dded56e870f12"
	  integrity sha512-tdzV+pJqNxfEdLMZIgIBOhdIxM04PWsWUKx9RdZlZBmo+28RV/lVNh77Qu4L74eNuDTn9CrKH3UmRPy9H0LlfQ==
	  dependencies:
		"@reactflow/core" "11.4.2"
		"@types/d3-selection" "^3.0.3"
		"@types/d3-zoom" "^3.0.1"
		classcat "^5.0.3"
		d3-selection "^3.0.0"
		d3-zoom "^3.0.0"
		zustand "^4.3.1"

	"@reactflow/node-toolbar@1.1.2":
	  version "1.1.2"
	  resolved "https://registry.npmjs.org/@reactflow/node-toolbar/-/node-toolbar-1.1.2.tgz#577c63429526950083663dd869bc2c53eca9ea36"
	  integrity sha512-zzG+s5jY9F1VbBh0na71AuarlQi8BHnkbd6mUCWJf50DPnmk05sEdurky7C9oNccm7wxEYBirBLyW4+1vnn4Nw==
	  dependencies:
		"@reactflow/core" "11.4.2"
		classcat "^5.0.3"
		zustand "^4.3.1"
		
	"@types/d3-array@*":
	  version "3.0.4"
	  resolved "https://registry.npmjs.org/@types/d3-array/-/d3-array-3.0.4.tgz#44eebe40be57476cad6a0cd6a85b0f57d54185a2"
	  integrity sha512-nwvEkG9vYOc0Ic7G7kwgviY4AQlTfYGIZ0fqB7CQHXGyYM6nO7kJh5EguSNA3jfh4rq7Sb7eMVq8isuvg2/miQ==

	"@types/d3-contour@*":
	  version "3.0.2"
	  resolved "https://registry.npmjs.org/@types/d3-contour/-/d3-contour-3.0.2.tgz#d8a0e4d12ec14f7d2bb6e59f3fbc1a527457d0b2"
	  integrity sha512-k6/bGDoAGJZnZWaKzeB+9glgXCYGvh6YlluxzBREiVo8f/X2vpTEdgPy9DN7Z2i42PZOZ4JDhVdlTSTSkLDPlQ==
	  dependencies:
		"@types/d3-array" "*"
		"@types/geojson" "*"

	"@types/d3-delaunay@*":
	  version "6.0.1"
	  resolved "https://registry.npmjs.org/@types/d3-delaunay/-/d3-delaunay-6.0.1.tgz#006b7bd838baec1511270cb900bf4fc377bbbf41"
	  integrity sha512-tLxQ2sfT0p6sxdG75c6f/ekqxjyYR0+LwPrsO1mbC9YDBzPJhs2HbJJRrn8Ez1DBoHRo2yx7YEATI+8V1nGMnQ==

	"@types/d3-drag@^3.0.1":
	  version "3.0.2"
	  resolved "https://registry.npmjs.org/@types/d3-drag/-/d3-drag-3.0.2.tgz#5562da3e7b33d782c2c1f9e65c5e91bb01ee82cf"
	  integrity sha512-qmODKEDvyKWVHcWWCOVcuVcOwikLVsyc4q4EBJMREsoQnR2Qoc2cZQUyFUPgO9q4S3qdSqJKBsuefv+h0Qy+tw==
	  dependencies:
		"@types/d3-selection" "*"

	"@types/d3-fetch@*":
	  version "3.0.2"
	  resolved "https://registry.npmjs.org/@types/d3-fetch/-/d3-fetch-3.0.2.tgz#fe1f335243e07c9bd520c9a71756fed8330c54b1"
	  integrity sha512-gllwYWozWfbep16N9fByNBDTkJW/SyhH6SGRlXloR7WdtAaBui4plTP+gbUgiEot7vGw/ZZop1yDZlgXXSuzjA==
	  dependencies:
		"@types/d3-dsv" "*"

	"@types/d3-scale-chromatic@*":
	  version "3.0.0"
	  resolved "https://registry.npmjs.org/@types/d3-scale-chromatic/-/d3-scale-chromatic-3.0.0.tgz#103124777e8cdec85b20b51fd3397c682ee1e954"
	  integrity sha512-dsoJGEIShosKVRBZB0Vo3C8nqSDqVGujJU6tPznsBJxNJNwMF8utmS83nvCBKQYPpjCzaaHcrf66iTRpZosLPw==

	"@types/d3-scale@*":
	  version "4.0.3"
	  resolved "https://registry.npmjs.org/@types/d3-scale/-/d3-scale-4.0.3.tgz#7a5780e934e52b6f63ad9c24b105e33dd58102b5"
	  integrity sha512-PATBiMCpvHJSMtZAMEhc2WyL+hnzarKzI6wAHYjhsonjWJYGq5BXTzQjv4l8m2jO183/4wZ90rKvSeT7o72xNQ==
	  dependencies:
		"@types/d3-time" "*"

	"@types/d3-selection@^3.0.3":
	  version "3.0.4"
	  resolved "https://registry.npmjs.org/@types/d3-selection/-/d3-selection-3.0.4.tgz#923d7f8985718116de56f55307d26e5f00728dc5"
	  integrity sha512-ZeykX7286BCyMg9sH5fIAORyCB6hcATPSRQpN47jwBA2bMbAT0s+EvtDP5r1FZYJ95R8QoEE1CKJX+n0/M5Vhg==

	"@types/d3-zoom@^3.0.1":
	  version "3.0.2"
	  resolved "https://registry.npmjs.org/@types/d3-zoom/-/d3-zoom-3.0.2.tgz#067aa6a6ecbc75a78b753cc6f7a7f9f7e4e7d117"
	  integrity sha512-t09DDJVBI6AkM7N8kuPsnq/3d/ehtRKBN1xSiYjjMCgbiw6HM6Ged5VhvswmhprfKyGvzeTEL/4WBaK9llWvlA==
	  dependencies:
		"@types/d3-interpolate" "*"
		"@types/d3-selection" "*"
		
	"@types/d3@^7.4.0":
	  version "7.4.0"
	  resolved "https://registry.npmjs.org/@types/d3/-/d3-7.4.0.tgz#fc5cac5b1756fc592a3cf1f3dc881bf08225f515"
	  integrity sha512-jIfNVK0ZlxcuRDKtRS/SypEyOQ6UHaFQBKv032X45VvxSJ6Yi5G9behy9h6tNTHTDGh5Vq+KbmBjUWLgY4meCA==
	  dependencies:
		"@types/d3-array" "*"
		"@types/d3-axis" "*"
		"@types/d3-brush" "*"
		"@types/d3-chord" "*"
		"@types/d3-color" "*"
		"@types/d3-contour" "*"
		"@types/d3-delaunay" "*"
		"@types/d3-dispatch" "*"
		"@types/d3-drag" "*"
		"@types/d3-dsv" "*"
		"@types/d3-ease" "*"
		"@types/d3-fetch" "*"
		"@types/d3-force" "*"
		"@types/d3-format" "*"
		"@types/d3-geo" "*"
		"@types/d3-hierarchy" "*"
		"@types/d3-interpolate" "*"
		"@types/d3-path" "*"
		"@types/d3-polygon" "*"
		"@types/d3-quadtree" "*"
		"@types/d3-random" "*"
		"@types/d3-scale" "*"
		"@types/d3-scale-chromatic" "*"
		"@types/d3-selection" "*"
		"@types/d3-shape" "*"
		"@types/d3-time" "*"
		"@types/d3-time-format" "*"
		"@types/d3-timer" "*"
		"@types/d3-transition" "*"
		"@types/d3-zoom" "*"

	classcat@^5.0.3:
	  version "5.0.4"
	  resolved "https://registry.npmjs.org/classcat/-/classcat-5.0.4.tgz#e12d1dfe6df6427f260f03b80dc63571a5107ba6"
	  integrity sha512-sbpkOw6z413p+HDGcBENe498WM9woqWHiJxCq7nvmxe9WmrUmqfAcxpIwAiMtM5Q3AhYkzXcNQHqsWq0mND51g==

	"d3-color@1 - 3":
	  version "3.1.0"
	  resolved "https://registry.npmjs.org/d3-color/-/d3-color-3.1.0.tgz#395b2833dfac71507f12ac2f7af23bf819de24e2"
	  integrity sha512-zg/chbXyeBtMQ1LbD/WSoW2DpC3I0mpmPdW+ynRTj/x2DAWYrIY7qeZIHidozwV24m4iavr15lNwIwLxRmOxhA==

	"d3-dispatch@1 - 3":
	  version "3.0.1"
	  resolved "https://registry.npmjs.org/d3-dispatch/-/d3-dispatch-3.0.1.tgz#5fc75284e9c2375c36c839411a0cf550cbfc4d5e"
	  integrity sha512-rzUyPU/S7rwUflMyLc1ETDeBj0NRuHKKAcvukozwhshr6g6c5d8zh4c2gQjY2bZ0dXeGLWc1PF174P2tVvKhfg==

	"d3-drag@2 - 3", d3-drag@^3.0.0:
	  version "3.0.0"
	  resolved "https://registry.npmjs.org/d3-drag/-/d3-drag-3.0.0.tgz#994aae9cd23c719f53b5e10e3a0a6108c69607ba"
	  integrity sha512-pWbUJLdETVA8lQNJecMxoXfH6x+mO2UQo8rSmZ+QqxcbyA3hfeprFgIT//HW2nlHChWeIIMwS2Fq+gEARkhTkg==
	  dependencies:
		d3-dispatch "1 - 3"
		d3-selection "3"

	"d3-ease@1 - 3":
	  version "3.0.1"
	  resolved "https://registry.npmjs.org/d3-ease/-/d3-ease-3.0.1.tgz#9658ac38a2140d59d346160f1f6c30fda0bd12f4"
	  integrity sha512-wR/XK3D3XcLIZwpbvQwQ5fK+8Ykds1ip7A2Txe0yxncXSdq1L9skcG7blcedkOX+ZcgxGAmLX1FrRGbADwzi0w==

	"d3-interpolate@1 - 3":
	  version "3.0.1"
	  resolved "https://registry.npmjs.org/d3-interpolate/-/d3-interpolate-3.0.1.tgz#3c47aa5b32c5b3dfb56ef3fd4342078a632b400d"
	  integrity sha512-3bYs1rOD33uo8aqJfKP3JWPAibgw8Zm2+L9vBKEHJ2Rg+viTR7o5Mmv5mZcieN+FRYaAOWX5SJATX6k1PWz72g==
	  dependencies:
		d3-color "1 - 3"

	"d3-selection@2 - 3", d3-selection@3, d3-selection@^3.0.0:
	  version "3.0.0"
	  resolved "https://registry.npmjs.org/d3-selection/-/d3-selection-3.0.0.tgz#c25338207efa72cc5b9bd1458a1a41901f1e1b31"
	  integrity sha512-fmTRWbNMmsmWq6xJV8D19U/gw/bwrHfNXxrIN+HfZgnzqTHp9jOmKMhsTUjXOJnZOdZY9Q28y4yebKzqDKlxlQ==

	"d3-timer@1 - 3":
	  version "3.0.1"
	  resolved "https://registry.npmjs.org/d3-timer/-/d3-timer-3.0.1.tgz#6284d2a2708285b1abb7e201eda4380af35e63b0"
	  integrity sha512-ndfJ/JxxMd3nw31uyKoY2naivF+r29V+Lc0svZxe1JvvIRmi8hUsrMvdOwgS1o6uBHmiz91geQ0ylPP0aj1VUA==

	"d3-transition@2 - 3":
	  version "3.0.1"
	  resolved "https://registry.npmjs.org/d3-transition/-/d3-transition-3.0.1.tgz#6869fdde1448868077fdd5989200cb61b2a1645f"
	  integrity sha512-ApKvfjsSR6tg06xrL434C0WydLr7JewBB3V+/39RMHsaXTOG0zmt/OAXeng5M5LBm0ojmxJrpomQVZ1aPvBL4w==
	  dependencies:
		d3-color "1 - 3"
		d3-dispatch "1 - 3"
		d3-ease "1 - 3"
		d3-interpolate "1 - 3"
		d3-timer "1 - 3"

	d3-zoom@^3.0.0:
	  version "3.0.0"
	  resolved "https://registry.npmjs.org/d3-zoom/-/d3-zoom-3.0.0.tgz#d13f4165c73217ffeaa54295cd6969b3e7aee8f3"
	  integrity sha512-b8AmV3kfQaqWAuacbPuNbL6vahnOJflOhexLzMMNLga62+/nh0JzvJ0aO/5a5MVgUFGS7Hu1P9P03o3fJkDCyw==
	  dependencies:
		d3-dispatch "1 - 3"
		d3-drag "2 - 3"
		d3-interpolate "1 - 3"
		d3-selection "2 - 3"
		d3-transition "2 - 3"

	reactflow@^11.4.2:
	  version "11.4.2"
	  resolved "https://registry.npmjs.org/reactflow/-/reactflow-11.4.2.tgz#8aeee24baf53bb7938ad41e57a6bbb4d84ca7261"
	  integrity sha512-kedccI6S/+/Fj+MFqEqb5bUncyTsr5DTxeAG5TZ6QB6wwNEE6KG3UFsqRaa1wbOtKnEWwOOupq0fDPE1ePUAZQ==
	  dependencies:
		"@reactflow/background" "11.1.2"
		"@reactflow/controls" "11.1.2"
		"@reactflow/core" "11.4.2"
		"@reactflow/minimap" "11.3.2"
		"@reactflow/node-toolbar" "1.1.2"

	use-sync-external-store@1.2.0:
	  version "1.2.0"
	  resolved "https://registry.npmjs.org/use-sync-external-store/-/use-sync-external-store-1.2.0.tgz#7dbefd6ef3fe4e767a0cf5d7287aacfb5846928a"
	  integrity sha512-eEgnFxGQ1Ife9bzYs6VLi8/4X6CObHMw9Qr9tPY43iKwsPw8xE8+EFsf/2cFZ5S3esXgpWgtSCtLNS41F+sKPA==

	use-sync-external-store@1.2.0:
	  version "1.2.0"
	  resolved "https://registry.npmjs.org/use-sync-external-store/-/use-sync-external-store-1.2.0.tgz#7dbefd6ef3fe4e767a0cf5d7287aacfb5846928a"
	  integrity sha512-eEgnFxGQ1Ife9bzYs6VLi8/4X6CObHMw9Qr9tPY43iKwsPw8xE8+EFsf/2cFZ5S3esXgpWgtSCtLNS41F+sKPA==

	zustand@^4.3.1:
	  version "4.3.2"
	  resolved "https://registry.npmjs.org/zustand/-/zustand-4.3.2.tgz#bb121fcad84c5a569e94bd1a2695e1a93ba85d39"
	  integrity sha512-rd4haDmlwMTVWVqwvgy00ny8rtti/klRoZjFbL/MAcDnmD5qSw/RZc+Vddstdv90M5Lv6RPgWvm1Hivyn0QgJw==
	  dependencies:
		use-sync-external-store "1.2.0"
`

**Comment by avishwakarmaplex** [comment]
It seems like updating d3 version to 7.8.2, solved the problem 

![image](https://user-images.githubusercontent.com/72560398/214064550-6bdee49e-d589-43b4-9a3c-1023ff6b96f7.png)

but unfortunately, it did broke my other components like charts and etc which had written in my library project

![image](https://user-images.githubusercontent.com/72560398/214064803-5c8eb277-28e1-4da3-99bb-7b50eff7707d.png)


FYI inorder to incorporate reactflow to my library project which uses webpack4, storybook 6.3.3 and didn't required @storybook/preset-create-react-app

I just had to add a rule
// webpack-extend.js
  config.module.rules.unshift({
    test: /\.js$/,
    include: /node_modules[\\\/]@?reactflow/,
    use: {
      loader: "babel-loader"
    }
  });

**Comment by Khedrak** [comment]
> It seems like updating d3 version to 7.8.2, solved the problem
> 
> ![image](https://user-images.githubusercontent.com/72560398/214064550-6bdee49e-d589-43b4-9a3c-1023ff6b96f7.png)
> 
> FYI inorder to incorporate reactflow to my library project which uses webpack4, storybook 6.3.3 and didn't required @storybook/preset-create-react-app
> 
> I just had to add a rule for transpile reactflow using babel-loader i believe // webpack-extend.js
> 
> ```
>   config.module.rules.unshift({
>     test: /\.js$/,
>     include: /node_modules[\\\/]@?reactflow/,
>     use: {
>       loader: "babel-loader"
>     }
>   });
>  
> ```

On my case, similar to this response i fixed up mine with the specific babel-loader for reactflow on webpack 4:

`{
                test: /\.js$/,
                include: [
                    path.resolve(__dirname, 'src'),
                    /node_modules[\/]@?reactflow/
                ],
                use: {
                    loader: 'babel-loader',
                    options: {
                        presets: [['@babel/preset-env', { 'modules': false }], '@babel/preset-react'],
                        plugins: [ "@babel/plugin-proposal-class-properties" ]
                    },
                },
            },`

**Comment by Jasminou** [comment]
SB still doesn't work with the latest version 11.5.1 even with the proposed solutions

**Comment by Jasminou** [comment]
while upgrading to the latest version of the reactflow I've the same probleme and the workaround here doesn't seem to work

**Comment by timto7** [comment]
I had the exact same problem and managed to fix it.

During compilation, I think more modern JS features such as the Nullish Coalescing Operator and Optional Chaining cause a bit of a commotion.

There are Babel plugins for dealing with them though, so I installed them:
`npm install --save-dev @babel/plugin-proposal-optional-chaining @babel/plugin-proposal-nullish-coalescing-operator`

Then I declared them in a **babel.config.rc** file:
```
{
  "plugins": [
    "@babel/plugin-proposal-optional-chaining",
    "@babel/plugin-proposal-nullish-coalescing-operator"
  ]
}
```

Then in the .storybook/main.js file, I added the rule @avishwakarmaplex prescribed earlier under **webpack**.

So ultimately my storybook main file looks like this:
```
module.exports = {
  stories: [
    '../src/**/*.stories.mdx',
    '../src/**/*.stories.@(js|jsx|ts|tsx)',
  ],
  addons: [
    '@storybook/addon-links',
    '@storybook/addon-essentials',
    '@storybook/addon-interactions',
  ],
  webpack: async (config) => {
    config.module.rules.unshift({
      test: /\.js$/,
      include: /node_modules[\\\/]@?reactflow/,
      use: {
        loader: 'babel-loader',
      }
    });

    return config;
  },
  framework: '@storybook/react',
  core: {
    builder: 'webpack4',
  }
};
```

I hope this helps.

**Comment by AdamGerthel** [comment]
I had the exact same problem when adding react-flow to an existing project that uses Webpack 4. This added webpack rule solved it for me:

```
      {
        test: /\.js$/,
        include: /node_modules[\\\/]@?reactflow/,
        use: {
          loader: 'babel-loader',
          options: {
            presets: [['@babel/preset-env'], '@babel/preset-react']
          }
        }
      },
```

**Comment by expspace** [comment]
@AdamGerthel 
Thanks this got me almost and after adding plugins this worked for me: 

```
    {
      test: /\.js$/,
      include: /node_modules[\\\/]@?reactflow/,
      use: {
        loader: 'babel-loader',
        options: {
          presets: ['@babel/preset-env', '@babel/preset-react'],
          plugins: ['@babel/plugin-proposal-optional-chaining', '@babel/plugin-proposal-nullish-coalescing-operator']
        }
      }
    }
```

**Comment by AdamGerthel** [comment]
@expspace That's odd - those plugins are part of preset-env so that shouldn't be needed, at least for ES2020. I added them as well first, but removed them, and it still worked. I'm currently not using them, without issues.

See https://babeljs.io/docs/babel-plugin-proposal-optional-chaining

**Comment by expspace** [comment]
@AdamGerthel Yeah it is strange it should be included with preset-env, but when I remove those plugins I get errors related to nullish coalescing and optional chaining. I am using the latest version of @babel/preset-env.

**Comment by Tomplach** [comment]
I tried for 2 days to solve the problem, finally it worked.

1)
npm i @babel/preset-env
npm i @babel/preset-react
npm i --save-dev @babel/plugin-proposal-optional-chaining
npm i --save-dev @babel/plugin-proposal-nullish-coalescing-operator

2)
Add this code to .storybook/main.js

`config.module.rules.push({
            test: /\.js$/,
            include: /node_modules[\\\/]@?reactflow/,
            use: {
                loader: 'babel-loader',
                options: {
                    presets: ['@babel/preset-env', '@babel/preset-react'],
                    plugins: ['@babel/plugin-proposal-optional-chaining', '@babel/plugin-proposal-nullish-coalescing-operator']
                }
            }
        });`
