### ISSUE TITLE
[Bug]: pathOptions borderRadius does not work correctly when connecting two vertically aligned nodes

### ISSUE THREAD

**Issue by binhtran04** [wbkd/react-flow#3205]
### Describe the Bug

I use pathOptions borderRadius: 20 to smoothstep edge. However, when two nodes are vertically aligned, the edges are not rounded. I happened with my own project and I was able to replicate in a code sandbox https://codesandbox.io/s/fast-fast-nhhj4q?file=/App.js:2525-2581

### Your Example Website or App

https://codesandbox.io/s/fast-fast-nhhj4q?file=/App.js:2525-2581

### Steps to Reproduce the Bug or Issue

1. Define edgeDefaultOptions as follow 
```
{
  type: "smoothstep",
  pathOptions: {
    borderRadius: 20,
    offset: 40
  }, 
}
```
2. Define two node vertically allined 
3. Define an edge from right handle of top node to right handle of bottom node and vice versa from left handle bottom node to left handle top node

### Expected behavior

The edges should be rounded according to borderRadius pathConfigs option

### Screenshots or Videos

![image](https://github.com/wbkd/react-flow/assets/15939436/1817dbb0-98ad-4fd0-b377-cba1ae1b286a)

### Platform

- OS: [Linux]
- Browser: [Chrome]
- Version: [reactflow 11.7.4]

**Comment by moklick** [comment]
That's a bug. Thanks for the report.

**Comment by GenaRazmakhnin** [comment]
hey! @moklick @binhtran04
I faced the same issue, it's affected not only vertically aligned nodes but horizontal as well, 
looks like I fixed the issue, but I do not have a lot time to find better solution please review :)

**Comment by moklick** [comment]
fixed in v11.8.0

**Comment by tomtitherington** [comment]
Just updated to v11.8.2 and this is still a problem for me. The edge has no corner radius when each edge is aligned horizontally with respect to each other but _also when they're not_ - see screenshots below. 

<img width="1035" alt="Screenshot 2023-08-16 at 12 32 33" src="https://github.com/wbkd/react-flow/assets/30439911/a1406aa0-0a66-4155-b7fa-2a7382b7f682">
<img width="1040" alt="Screenshot 2023-08-16 at 12 32 46" src="https://github.com/wbkd/react-flow/assets/30439911/1d6c00f1-35e4-45fd-b1e3-3b59d75eabee">

**Comment by moklick** [comment]
@tomtitherington I'll check that

**Comment by moklick** [comment]
How can I reproduce this @tomtitherington - this looks good to me https://codesandbox.io/s/unruffled-lake-thhftj?file=/src/Flow.tsx

**Comment by moklick** [comment]
Is this still an issue with 11.8.3 @tomtitherington ?

**Comment by tomtitherington** [comment]
Sorry for the slow reply, thanks for checking in @moklick.

When I use the edgeDefaultOptions argument this seems to work but when using the `getSmoothStepPath` function within a custom edge I still seem to have issues. 

```import React from "react";
import { EdgeProps, getSmoothStepPath } from "reactflow";

import styles from "./EdgeTypes.module.css";
import useEdgeClick from "hooks/useEdgeClick";

export default function CustomEdge({
  id,
  sourceX,
  sourceY,
  targetX,
  targetY,
  sourcePosition,
  targetPosition,
  style,
  markerEnd,
}: EdgeProps) {
  // see the hook for implementation details
  // onClick adds a node in between the nodes that are connected by this edge
  const onClick = useEdgeClick(id);

  const [edgePath, edgeCenterX, edgeCenterY] = getSmoothStepPath({
    sourceX,
    sourceY,
    sourcePosition,
    targetX,
    targetY,
    targetPosition,
  });

  return (
    <>
      <path
        id={id}
        style={style}
        className={styles.edgePath}
        d={edgePath}
        markerEnd={markerEnd}
      />
      <g transform={`translate(${edgeCenterX}, ${edgeCenterY})`}>
        <rect
          onClick={onClick}
          x={-10}
          y={-10}
          width={20}
          ry={4}
          rx={4}
          height={20}
          className={styles.edgeButton}
        />
        <text className={styles.edgeButtonText} y={5} x={-5}>
          +
        </text>
      </g>
    </>
  );
}```

However it's possible that I'm doing something wrong elsewhere in the code... Sadly, I haven't had time to put together a minimal reproducible example - feel free to close this.

**Comment by moklick** [comment]
thanks, I will have a look

**Comment by moklick** [comment]
@tomtitherington please re-open with a codesandbox. I am not able to reproduce it.

**Comment by andrijan** [comment]
Here is an example where the Node 2 doesn't have the correct target radius, but Node 3 does.

https://codesandbox.io/embed/fragrant-microservice-cctpkq?fontsize=14&hidenavigation=1&theme=dark

**Comment by moklick** [comment]
Hey @andrijan , thanks for the codesandbox! We will check it.
